<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260421181731 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "orders" (uuid UUID NOT NULL, is_payed BOOLEAN NOT NULL, is_finish BOOLEAN NOT NULL, PRIMARY KEY (uuid))');
        $this->addSql('CREATE TABLE orders_products (order_uuid UUID NOT NULL, product_id INT NOT NULL, PRIMARY KEY (order_uuid, product_id))');
        $this->addSql('CREATE INDEX IDX_749C879C9C8E6AB1 ON orders_products (order_uuid)');
        $this->addSql('CREATE INDEX IDX_749C879C4584665A ON orders_products (product_id)');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price INT NOT NULL, state VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE orders_products ADD CONSTRAINT FK_749C879C9C8E6AB1 FOREIGN KEY (order_uuid) REFERENCES "orders" (uuid) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE orders_products ADD CONSTRAINT FK_749C879C4584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE orders_products DROP CONSTRAINT FK_749C879C9C8E6AB1');
        $this->addSql('ALTER TABLE orders_products DROP CONSTRAINT FK_749C879C4584665A');
        $this->addSql('DROP TABLE "orders"');
        $this->addSql('DROP TABLE orders_products');
        $this->addSql('DROP TABLE products');
    }
}
